@startuml
title "add a threaded comment flow"

actor User as user
participant BFF as bff
participant Comment as comment
participant Inbox as inbox
participant Push as push
queue Kafka as kafka

user -> bff: add a comment on a comment
bff -> comment: comment add request
comment -> comment: check if parent comment exists
alt if not exist
user <- bff: error response
end
comment -> comment: insert comment
bff <- comment: response
user <- bff: response
comment --> kafka: publish comment_created event
kafka --> inbox: comsume comment_created event
inbox -> comment: request comment info
alt if exists
inbox -> comment: request parent comment author id
inbox -> inbox: insert/update user inbox info
inbox -> push: request push notification reservation
end
@enduml
