@startuml
title "delete a comment on a comment flow"

actor User as user
participant BFF as bff
participant Comment as comment
participant Media as media
participant Inbox as inbox
participant Push as push
participant Like as like
queue Kafka as kafka

user -> bff: delete a comment on a comment
bff -> media: check if the comment exists
alt if not exist
user <- bff: error response
end
bff -> comment: comment delete request
comment -> comment: delete comment
alt if not exist
bff <- comment: error response
user <- bff: error response
end
bff <- comment: response
user <- bff: response
comment --> kafka: publish comment_deleted event(w/ parent comment id)
kafka --> inbox: comsume comment_deleted event
inbox -> comment: request comment info
alt if not exist
inbox -> comment: request parent comment author id
inbox -> inbox: delete/update user inbox info
end
like <-- kafka: consume comment_deleted event
like -> like: delete all like info
@enduml
