@startuml
title "comment unlike flow"

actor User as user
participant BFF as bff
participant Comment as comment
participant Like as like
participant Inbox as inbox
participant Push as push
queue Kafka as kafka

user -> bff: unlike a comment
bff -> comment: check if the comment exists
alt if not exist
user <- bff: error response
end
bff -> like: unlike request
like -> like: delete like info\n(Do nothing if not found)
bff <- like: response
user <- bff: response
like --> kafka: publish like_deleted(w/ comment id) event
kafka --> inbox: comsume like_deleted event
inbox -> like: request like info
alt if not exist
inbox -> comment: request comment author id
inbox -> inbox: insert/update user inbox info
end
@enduml
