### list collections
GET {{host}}/api/v1/collections/list?max_id=9999

### delete collection
POST {{host}}/api/v1/collections/create
Content-Type: application/json

{
  "name": "my collection",
  "added_media_ids": [
    "1"
  ]
}

