# https://github.com/frederikheld/render-plantuml-to-wiki-action/tree/master

name: generate plantuml to Wiki
on: push
jobs:
  generate_plantuml:
    permissions: write-all
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Render PlantUML to wiki(comment)
      uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
      with:
        WIKI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_DIR: 'uml/sequence/comment'
        OUTPUT_DIR: 'uml/generated'
    - name: Render PlantUML to wiki(like)
      uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
      with:
        WIKI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_DIR: 'uml/sequence/like'
        OUTPUT_DIR: 'uml/generated'
